name: 'GitHub App Checkout'
description: 'Checkout repository with GitHub App authentication and submodules'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App private key'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        submodules: recursive
        persist-credentials: false